name: shimmer_server
description: Server code for shimmer
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev
  shimmer_shared: any

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  lints: any
