name: shimmer_shared
description: Shared code between client and server for Shimmer.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  radiance:
    git:
      url: https://github.com/flame-engine/radiance
      ref: 13161dd # commit hash

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
